model:
  base_learning_rate: 1.0e-6   # set to target_lr by starting main.py with '--scale_lr False', defalut is 5.0e-5
  target: ldm.models.diffusion.ddpm_HSI.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 128
    channels: 9
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: False
    scale_factor : 5.0
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 0.01]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128
        in_channels: 9
        out_channels: 9
        model_channels: 320
        attention_resolutions: [ 4, 8 ]
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]  # 1 2 4 8
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.hsi_encoder.VCA
      params:
        in_channels: 103
        out_channels: 9
        ckpt_path: "models/first_stage_models/HSI/VCA/PaviaU/model.ckpt"

    cond_stage_config: "__is_unconditional__"

data:
  target: main_HSI.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 4
    wrap: False
    train:
      target: ldm.data.HSI.PaviaU_train
      params:
        image_size: 128
    validation:
      target: ldm.data.HSI.PaviaU_valid
      params:
        image_size: 128

lightning:
  callbacks:
    image_logger:
      target: main_HSI.ImageLogger_HSI
      params:
        batch_frequency: 800
        max_images: 8
        increase_log_steps: False
        visual_channels: [46,27,10]
        log_images_kwargs:
          quantize_denoised: False
          inpaint : False
          plot_denoise_rows : False
          plot_progressive_rows : True
          plot_diffusion_rows : True


  trainer:
    benchmark: True
    max_epochs: 10000